### ISSUE TITLE
the current chainer-mask-rcnn is unadaptable to the latest chainer version

### ISSUE THREAD

**Issue by himlen1990** [wkentaro/chainer-mask-rcnn#40]
Failures occurred when running train.py in the example/custom_dataset/ 
I had tried some chainer versions (7.7.0 and 6.6.0) and failed.
(the error in 6.6.0 )
Exception in main training loop: Extension implementation must override __call__.
Traceback (most recent call last):
  File "/home/pr2/anaconda2/envs/chainer-mrcnn/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/pr2/anaconda2/envs/chainer-mrcnn/lib/python3.6/site-packages/chainer/training/extension.py", line 65, in __call__
    'Extension implementation must override __call__.')
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    main()
  File "train.py", line 88, in main
    evaluator_type='voc',
  File "/home/pr2/chainer-mask-rcnn/examples/custom_dataset/../train_common.py", line 354, in train
    trainer.run()
  File "/home/pr2/anaconda2/envs/chainer-mrcnn/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/pr2/anaconda2/envs/chainer-mrcnn/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/pr2/anaconda2/envs/chainer-mrcnn/lib/python3.6/site-packages/chainer/training/trainer.py", line 319, in run
    entry.extension(self)
  File "/home/pr2/anaconda2/envs/chainer-mrcnn/lib/python3.6/site-packages/chainer/training/extension.py", line 65, in __call__
    'Extension implementation must override __call__.')
NotImplementedError: Extension implementation must override __call__.
-------------------------------------------------------------------------------

Finally I installed chainer 4.0.0 and it worked. It seems the current chainer-mask-rcnn is not support chainer version higher than 5.0.0, I think you'd better to modify the requirements.txt.

**Comment by knorth55** [comment]
@himlen1990 can you try this PR?  https://github.com/wkentaro/fcn/pull/121
this PR fix the same issues occurred in my env.
